services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code

    ports:
      - 8000:8000

    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - "DJANGO_SECRET_KEY=django-insecure-3870%(y^dev_x=wx8atbovoy_vpigc9p6vuwjc=)0y5*bf2c=a"
      - "DJANGO_DEBUG=True"

    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data

    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
